name: Run JavaScript File
on:
  push:
    branches:
      - main # Modify to match your repository's default branch
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  run-js-file:
    runs-on: ubuntu-latest

    steps:
      - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript file
        run: node .github/scripts/logs.js # Replace with the actual filename of your JavaScript file
